#!/bin/bash
CPAN_SITE="http://cpan.perl.org/modules/by-module"
DEBIAN_SITE="http://ftp.debian.org/debian/pool"
FREEDESKTOP_SITE="http://freedesktop.org/software"
GNOME_SITE="http://ftp.gnome.org/pub/GNOME/sources"
GNU_SITE="http://mirrors.kernel.org/gnu"
KERNEL_SITE="http://www.kernel.org/pub/linux"
MOZILLA_SITE="http://ftp.mozilla.org/pub"
NONGNU_SITE="http://download.savannah.nongnu.org/releases"
PYPI_SITE="https://files.pythonhosted.org/packages/source"
SOURCEFORGE_SITE="http://downloads.sourceforge.net/sourceforge"
UBUNTU_SITE="http://archive.ubuntu.com/ubuntu/pool"
XORG_HOME="http://xorg.freedesktop.org/wiki/"
XORG_SITE="http://xorg.freedesktop.org/releases/individual"
set -e
function print_usage(){
    cat << EOF
Usage: $(basename $0)" <template file>
EOF
}

function abort(){
    echo "Error: $@"
    print_usage
    exit -1
}

if [ "x$1" == "x-h" ] || [ "x$1" == "x--help" ];then
    print_usage
    exit 0
fi
TEMPLATE_FILE=$1
[ -z "$TEMPLATE_FILE" ] && abort "Arguments missing!"
[ -f "$TEMPLATE_FILE" ] || abort "File $TEMPLATE_FILE not found!"
source <(grep -v '^ \|^configure\|^makedepends\|^hostmakedepends' "$TEMPLATE_FILE")
for url in "$distfiles"; do
    curl $url | sha256sum
done
