#!/bin/bash
set -e
CPAN_SITE="http://cpan.perl.org/modules/by-module"
DEBIAN_SITE="http://ftp.debian.org/debian/pool"
FREEDESKTOP_SITE="http://freedesktop.org/software"
GNOME_SITE="http://ftp.gnome.org/pub/GNOME/sources"
GNU_SITE="http://mirrors.kernel.org/gnu"
KERNEL_SITE="http://www.kernel.org/pub/linux"
MOZILLA_SITE="http://ftp.mozilla.org/pub"
NONGNU_SITE="http://download.savannah.nongnu.org/releases"
PYPI_SITE="https://files.pythonhosted.org/packages/source"
SOURCEFORGE_SITE="http://downloads.sourceforge.net/sourceforge"
UBUNTU_SITE="http://archive.ubuntu.com/ubuntu/pool"
XORG_HOME="http://xorg.freedesktop.org/wiki/"
XORG_SITE="http://xorg.freedesktop.org/releases/individual"

CURL_OPTS="--location"
function print_usage(){
    cat << EOF
Usage: $(basename $0)" [options] <template file>

Valid options are:
    -d,--debug
        print debug output
    -h,--help
        print this help
    -k,--keep
        keep downloaded files
EOF
}

function abort(){
    echo "Error: $@"
    print_usage
    exit -1
}

KEEP="n"
while [ $# -gt 0 ];do
    if [ "x$NO_OPTS" == "xy" ] && [[ "$1" =~ \-.* ]];then
        ARGS+="$1 "
    else
        case $1 in 
            '--')
                NO_OPTS="y"
                ;;
            '-d'|'--debug')
                set -xe
                ;;
            '-k'|'--keep')
                KEEP="y"
                ;;
            '-h'|'--help')
                print_usage
                exit 0
                ;;
            *)
                [ -z "$TEMPLATE_FILE" ] || abort "Too many arguments!"
                TEMPLATE_FILE=$1
                ;;
        esac
    fi
    shift
done

[ -z "$TEMPLATE_FILE" ] && abort "Arguments missing!"
[ -f "$TEMPLATE_FILE" ] || abort "File $TEMPLATE_FILE not found!"
source <(grep -v '^ \|^configure\|^makedepends\|^hostmakedepends' "$TEMPLATE_FILE")
for url in "$distfiles"; do
    echo "Requesting \"${url}\""
    if [ "x${KEEP}" == "xy" ];then
        FILENAME=${url##*/}
        curl ${CURL_OPTS} $url -o ./$FILENAME 
        sha256sum ./$FILENAME
    else    
        curl ${CURL_OPTS} $url | sha256sum
    fi
done
